# Generated by Django 5.1.2 on 2024-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(max_length=255)),
                ('face_encoding', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('occurrences', models.IntegerField(default=1)),
                ('quality_score', models.FloatField(default=0.0)),
                ('device_id', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=255)),
            ],
        ),
    ]
