# Generated by Django 5.1.2 on 2024-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_manager', '0002_unregisteredfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
