# Generated by Django 5.1.2 on 2024-11-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_manager', '0003_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='unregistered_face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.unregisteredfaces'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.person'),
        ),
    ]
